### ISSUE TITLE
Require sf2.8 ?

### ISSUE THREAD

**Issue by mysterty** [Discutea/DForumBundle#1]
Hello,

As sf3 haven't yet main bundles but is fully compatible sf2.8, can you change your dependencies ?
I tested with my own 2.8 project and almost all works... except `form_rest(form)` in `Topic.html.twig`

> LogicException: Unable to render the form as none of the following blocks exist: "_forumbundle_topic_rest", "forumbundle_topic_rest", "forumbundle_topic_rest", "form_rest".

**Comment by Strategy47** [comment]
Hi, 
This is fixed in dev-master. I have to do more tests before leaving a release.
There are still issues. Unfortunately, I can't fix them because of sf 3.1 compatibility errors.
See deprecated: https://travis-ci.org/Discutea/DForumBundle/jobs/136663066
Please can you confirm that it works before closing this issue.

**Comment by mysterty** [comment]
for me everything works now, tested with sf2.8
